version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - socket:/socket
    ports:
      - 80:80
    depends_on:
      - "flask"
    networks:
      - all
  db:
    image: mariadb:10.5.8-focal
    container_name: production_db
    volumes:
      - db:/var/lib/mysql
    networks:
      - all
  flask:
      tty: true
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        DATABASE_URL: mysql+pymysql://archive:Meeloomi3coo2ahthaitahg0eingiido@db/archive
      depends_on:
        - db
      expose:
        - 3000
      command: uwsgi --ini ./uwsgi.ini
      volumes:
        - socket:/socket
      networks:
        - all
      stop_grace_period: 30s
      deploy:
        replicas: 3
        update_config:
          delay: 10m
          parallelism: 1
          failure_action: rollback
volumes:
  db:
  socket:
networks:
  all: