version: "3.8"
services:
  redis:
    image: redis:6.0.9-alpine
    networks:
      - all
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - socket:/socket
      - /srv/www/static:/srv/www/static
    ports:
      - 80:80
    networks:
      - all
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  db:
    image: mariadb:10.5.8-focal
    container_name: production_db
    volumes:
      - db:/var/lib/mysql
    networks:
      - all
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  flask:
      image: chatpic-docker:latest
      environment:
        DATABASE_URL: mysql+pymysql://archive:Meeloomi3coo2ahthaitahg0eingiido@db/archive
        SECRET_KEY: ong4eivu7Ies2thaep6juowoh2ooYe8eox2ba7oocaik4aemieshiXozaf6Fee6E
        FILE_STORAGE_LOCATION: /srv/www/static/
        CDN_URL: https://media.chatpic.exposed/
        DEBUG: "False"
        STORAGE_URL: redis://redis:6379
        CACHE_TYPE: filesystem
        CACHE_DIR: /tmp/cache
      command: uwsgi --ini ./uwsgi.ini
      volumes:
        - socket:/socket
        - /srv/www/static:/srv/www/static
      networks:
        - all
      stop_grace_period: 30s
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
        update_config:
          delay: 1m
          parallelism: 1
          failure_action: rollback
volumes:
  db:
  socket:
networks:
  all: